-- Safe Return schema for Safety Guardian
-- Run this in the Supabase SQL Editor after the base `profiles` table already exists.

create table if not exists public.safe_return_profiles (
  user_id uuid references public.profiles(id) primary key,
  destination_name text not null,
  destination_address text not null,
  alert_after_minutes integer default 30,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.safe_return_contacts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  name text not null,
  phone text not null,
  priority integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.safe_return_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  destination_name text not null,
  destination_address text not null,
  status text default 'active',
  alert_after_minutes integer default 30,
  started_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ended_at timestamp with time zone,
  last_latitude double precision,
  last_longitude double precision,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.safe_return_profiles enable row level security;
alter table public.safe_return_contacts enable row level security;
alter table public.safe_return_sessions enable row level security;

drop policy if exists "Users can view own safe return profile" on public.safe_return_profiles;
drop policy if exists "Users can insert own safe return profile" on public.safe_return_profiles;
drop policy if exists "Users can update own safe return profile" on public.safe_return_profiles;

create policy "Users can view own safe return profile"
on public.safe_return_profiles
for select
using (auth.uid() = user_id);

create policy "Users can insert own safe return profile"
on public.safe_return_profiles
for insert
with check (auth.uid() = user_id);

create policy "Users can update own safe return profile"
on public.safe_return_profiles
for update
using (auth.uid() = user_id);

drop policy if exists "Users can view own safe return contacts" on public.safe_return_contacts;
drop policy if exists "Users can insert own safe return contacts" on public.safe_return_contacts;
drop policy if exists "Users can update own safe return contacts" on public.safe_return_contacts;
drop policy if exists "Users can delete own safe return contacts" on public.safe_return_contacts;

create policy "Users can view own safe return contacts"
on public.safe_return_contacts
for select
using (auth.uid() = user_id);

create policy "Users can insert own safe return contacts"
on public.safe_return_contacts
for insert
with check (auth.uid() = user_id);

create policy "Users can update own safe return contacts"
on public.safe_return_contacts
for update
using (auth.uid() = user_id);

create policy "Users can delete own safe return contacts"
on public.safe_return_contacts
for delete
using (auth.uid() = user_id);

drop policy if exists "Users can view own safe return sessions" on public.safe_return_sessions;
drop policy if exists "Users can insert own safe return sessions" on public.safe_return_sessions;
drop policy if exists "Users can update own safe return sessions" on public.safe_return_sessions;

create policy "Users can view own safe return sessions"
on public.safe_return_sessions
for select
using (auth.uid() = user_id);

create policy "Users can insert own safe return sessions"
on public.safe_return_sessions
for insert
with check (auth.uid() = user_id);

create policy "Users can update own safe return sessions"
on public.safe_return_sessions
for update
using (auth.uid() = user_id);
