-- 안전 지킴이 Supabase Schema

-- 1. Profiles (회원 확장 정보)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  nickname TEXT UNIQUE,
  level INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname)
  VALUES (new.id, new.raw_user_meta_data->>'nickname');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 2. Reports (신고 접수 내역)
CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  image_url TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Safety Feed (우리 동네 커뮤니티 피드)
CREATE TABLE safety_feed (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  location_name TEXT,
  danger_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Safe Return Profile (안심 귀가 개인 설정)
CREATE TABLE safe_return_profiles (
  user_id UUID REFERENCES public.profiles(id) PRIMARY KEY,
  destination_name TEXT NOT NULL,
  destination_address TEXT NOT NULL,
  alert_after_minutes INTEGER DEFAULT 30,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Safe Return Contacts (보호자 연락망)
CREATE TABLE safe_return_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  priority INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. Safe Return Sessions (귀가 세션 기록)
CREATE TABLE safe_return_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  destination_name TEXT NOT NULL,
  destination_address TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  alert_after_minutes INTEGER DEFAULT 30,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE,
  last_latitude DOUBLE PRECISION,
  last_longitude DOUBLE PRECISION,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE safety_feed ENABLE ROW LEVEL SECURITY;
ALTER TABLE safe_return_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE safe_return_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE safe_return_sessions ENABLE ROW LEVEL SECURITY;

-- Profiles 정책
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Reports 정책
CREATE POLICY "Reports viewable by everyone" ON reports FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert reports" ON reports FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Feed 정책
CREATE POLICY "Feeds viewable by everyone" ON safety_feed FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert feeds" ON safety_feed FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Safe return profile 정책
CREATE POLICY "Users can view own safe return profile" ON safe_return_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can upsert own safe return profile" ON safe_return_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own safe return profile" ON safe_return_profiles FOR UPDATE USING (auth.uid() = user_id);

-- Safe return contacts 정책
CREATE POLICY "Users can view own safe return contacts" ON safe_return_contacts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own safe return contacts" ON safe_return_contacts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own safe return contacts" ON safe_return_contacts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own safe return contacts" ON safe_return_contacts FOR DELETE USING (auth.uid() = user_id);

-- Safe return sessions 정책
CREATE POLICY "Users can view own safe return sessions" ON safe_return_sessions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own safe return sessions" ON safe_return_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own safe return sessions" ON safe_return_sessions FOR UPDATE USING (auth.uid() = user_id);
